apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/pytorch-operator
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/pytorch-operator
  newTag: v0.7.0
