apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- crd.yaml
- deployment.yaml
- service.yaml
- service-account.yaml
namePrefix: profiles-
namespace: kubeflow
commonLabels:
  kustomize.component: profiles
configMapGenerator:
- name: profiles-parameters
  env: params.env
images:
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/profile-controller
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/profile-controller
  newTag: 9b834c9d44
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/kfam
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/kfam
  newTag: 3b0d4be7e5
vars:
- name: admin
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.admin
- name: gcp-sa
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.gcp-sa
- name: userid-header
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.userid-header
- name: userid-prefix
  objref:
    kind: ConfigMap
    name: profiles-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.userid-prefix
- name: namespace
  objref:
    kind: Service
    name: kfam
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
configurations:
- params.yaml
