apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameprefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-persistenceagent
resources:
- clusterrole-binding.yaml
- clusterrole.yaml
- deployment.yaml
- service-account.yaml
images:
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/persistenceagent
  newTag: 0.1.31
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/persistenceagent
