apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameprefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-visualizationserver
resources:
- deployment.yaml
- service.yaml
images:
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/visualization-server
  newTag: 0.1.27
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/visualization-server