apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
nameprefix: ml-pipeline-viewer-
commonLabels:
  app: ml-pipeline-viewer-crd
resources:
- crd.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
images:
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/viewer-crd-controller
  newTag: 0.1.31
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/viewer-crd-controller
