apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-ui
  labels:
    app: katib
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katib
      component: ui
  template:
    metadata:
      name: katib-ui
      labels:
        app: katib
        component: ui
    spec:
      containers:
      - name: katib-ui
        image: registry.cn-zhangjiakou.aliyuncs.com/aimyth/katib-ui
        imagePullPolicy: IfNotPresent
        command:
          - './katib-ui'
        env:
          - name: KATIB_CORE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: ui
          containerPort: 80
      serviceAccountName: katib-ui
