apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- role-binding.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- apiservice.yaml
- image.yaml
- hpa.yaml
commonLabels:
  kustomize.component: knative
images:
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/activator
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/activator
  newTag: 88d864eb3c
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/autoscaler-hpa
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/autoscaler-hpa
  newTag: a7801c3cf4
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/autoscaler
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/autoscaler
  newTag: aeaacec4fe
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/istio
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/istio
  newTag: 057c999bcc
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/webhook
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/webhook
  newTag: c207667461
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/controller
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/controller
  newTag: 3b096e55fa
