apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- job.yaml
- certificate.yaml
namespace: kubeflow
commonLabels:
  kustomize.component: iap-ingress
images:
- name: registry.cn-zhangjiakou.aliyuncs.com/aimyth/ingress-setup
  newName: registry.cn-zhangjiakou.aliyuncs.com/aimyth/ingress-setup
  newTag: unknown
